server:
  port: ${PORT:2019}
  error:
    whitelabel:
      enabled: false

# h2 config. Remove for deployment.
spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  jackson:
    serialization: false

#need for Postgresql, shouldn't need until deployment
#change the following line to point to your postgres database
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Lambda-sprint-bookstore}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
